#pragma once
static const char CALENDAR_PAGE[]=R"HTML(<h1>班表與鬧鐘</h1><p>選擇月份，點選上班日期，或上傳班表圖片自動填入。確認日期與響鈴時間後儲存。</p><label>月份<input id="month" type="month" min="2024-01" max="2099-12"></label><form id="upload"><label class="upload-box">班表圖片<input id="image" type="file" accept="image/jpeg,image/png,image/webp"></label><button id="recognize" type="submit">辨識並填入月曆</button><button id="cancel" type="button" hidden>取消辨識</button><p id="ai-status" role="status" aria-live="polite">圖片辨識需要網路；無法辨識時仍可直接點選日期。</p></form><div class="calendar" id="weekdays"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class="calendar" id="days"></div><p id="count"></p><p class="help">紅點與細紅框：今天 · 深色：會響鈴的上班日 · 深色外框：連續上班但不重複響鈴 · 淺色：休假 · 橙色：需要確認。</p><button id="clear" class="secondary" type="button">清除本月上班日</button><h2>上班日響鈴時間</h2><p>每個需要通知的上班日使用下列時間，最多八個；每一個時間都能獨立開啟或關閉。</p><div id="times"></div><button id="add" class="secondary" type="button">＋ 新增鬧鐘時間</button><label class="check-option"><input id="first-only" type="checkbox">連續上班只通知第一天</label><p class="help">勾選後，連續上班的第一天維持深色，其餘上班日只顯示深色外框，不會建立鬧鐘。</p><p class="help">所有日期與響鈴時間固定使用臺北時間（UTC+8）。儲存只更新這個月份；通知方式套用到所有已儲存月份。</p><button id="save" type="button">儲存班表與鬧鐘</button><p id="status" role="status" aria-live="polite"></p><button id="clock" type="button" hidden>使用此手機時間校時</button><p><a href="/display">裝置設定與時鐘校對</a> · <a href="/tailnet">Tailscale 連線</a></p><script>
const nonce='NONCE',month=document.querySelector('#month'),statusEl=document.querySelector('#status'),aiStatus=document.querySelector('#ai-status');let selected=new Set(),review=new Set(),alarmTimes=[],disabledTimes=new Set(),busy=false,dirty=false,loadedMonth='',loadSeq=0,controller=null,mixedTimes=false,previousDayWork=false;
const pad=n=>String(n).padStart(2,'0');
function controls(){for(const id of ['month','clear','add','save','recognize','image','first-only'])document.getElementById(id).disabled=busy;document.getElementById('save').disabled=busy||loadedMonth!==month.value;document.querySelector('#cancel').hidden=!controller;draw();drawTimes()}
function draw(){const [y,m]=month.value.split('-').map(Number),grid=document.querySelector('#days'),firstOnly=document.querySelector('#first-only').checked;grid.replaceChildren();if(!y||!m)return;for(let i=0;i<new Date(y,m-1,1).getDay();i++)grid.append(document.createElement('span'));for(let day=1;day<=new Date(y,m,0).getDate();day++){const b=document.createElement('button'),silent=firstOnly&&selected.has(day)&&(day===1?previousDayWork:selected.has(day-1));b.type='button';b.textContent=day;b.className=review.has(day)?'reviewday':silent?'silent-workday':selected.has(day)?'workday':'';b.setAttribute('aria-pressed',selected.has(day));b.dataset.label=`${m}月${day}日，${review.has(day)?'待確認':silent?'上班、不重複響鈴':selected.has(day)?'上班、會響鈴':'休假'}`;b.setAttribute('aria-label',b.dataset.label);b.disabled=busy;b.onclick=()=>{if(review.delete(day))selected.add(day);else selected.has(day)?selected.delete(day):selected.add(day);dirty=true;draw()};grid.append(b)}refreshTodayMarker();const silentCount=firstOnly?[...selected].filter(day=>day===1?previousDayWork:selected.has(day-1)).length:0;document.querySelector('#count').textContent=`${selected.size} 天上班${silentCount?' · '+(selected.size-silentCount)+' 天會響鈴':''}${review.size?' · '+review.size+' 天待確認':''}`}
function drawTimes(){const wrap=document.querySelector('#times');wrap.replaceChildren();alarmTimes.forEach((value,i)=>{const row=document.createElement('div');row.className='time-row';const title=document.createElement('strong');title.textContent='鬧鐘 '+(i+1);row.append(title);const [hour,minute]=value.split(':');for(const [unit,current,max] of [['時',hour,24],['分',minute,60]]){const label=document.createElement('label'),select=document.createElement('select');select.setAttribute('aria-label',`第 ${i+1} 個鬧鐘的${unit}`);for(let n=0;n<max;n++){const o=document.createElement('option');o.value=pad(n);o.textContent=pad(n)+' '+unit;select.append(o)}select.value=current;select.disabled=busy;select.onchange=()=>{const old=alarmTimes[i],parts=old.split(':');parts[unit==='時'?0:1]=select.value;alarmTimes[i]=parts.join(':');if(disabledTimes.delete(old))disabledTimes.add(alarmTimes[i]);dirty=true;drawTimes()};label.append(select);row.append(label)}const enableLabel=document.createElement('label');enableLabel.className='alarm-enable';const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=!disabledTimes.has(value);enabled.disabled=busy;enabled.setAttribute('aria-label',`啟用第 ${i+1} 個鬧鐘`);enabled.onchange=()=>{const current=alarmTimes[i];enabled.checked?disabledTimes.delete(current):disabledTimes.add(current);dirty=true};enableLabel.append(enabled,document.createTextNode('啟用'));row.append(enableLabel);const remove=document.createElement('button');remove.className='secondary';remove.type='button';remove.textContent='移除';remove.setAttribute('aria-label',`移除第 ${i+1} 個鬧鐘`);remove.disabled=busy;remove.onclick=()=>{disabledTimes.delete(alarmTimes[i]);alarmTimes.splice(i,1);dirty=true;drawTimes()};row.append(remove);wrap.append(row)});document.querySelector('#add').disabled=busy||alarmTimes.length>=8;if(!alarmTimes.length){const p=document.createElement('p');p.textContent='尚未設定響鈴時間。';wrap.append(p)}}
async function request(url,options={}){const r=await fetch(url,{...options,headers:{'X-Setup-Nonce':nonce,...options.headers}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{}if(!r.ok)throw Error(typeof data?.detail==='string'?data.detail:typeof data?.error==='string'?data.error:text||'服務暫時無法回應');if(!data)throw Error('服務回應格式無效');return data}
async function waitForSave(id){const deadline=Date.now()+20000;while(Date.now()<deadline){const result=await request('/api/local-calendar/save-status?id='+id);if(result.state==='saved')return;if(result.state==='error')throw Error(result.message);await new Promise(resolve=>setTimeout(resolve,100))}throw Error('儲存逾時，請重新讀取班表確認')}
async function load(){const seq=++loadSeq;busy=true;controls();statusEl.textContent='正在讀取班表…';try{const d=await request('/api/local-calendar?month='+encodeURIComponent(month.value));if(seq!==loadSeq)return;selected=new Set(d.days);review.clear();alarmTimes=d.times;disabledTimes=new Set(Array.isArray(d.disabled_times)?d.disabled_times:[]);mixedTimes=Boolean(d.mixed_times);previousDayWork=Boolean(d.previous_day_work);document.querySelector('#first-only').checked=Boolean(d.first_consecutive_only);loadedMonth=month.value;dirty=false;document.querySelector('#clock').hidden=d.clock_ready;statusEl.textContent=d.clock_ready?'點選上班日期，設定響鈴時間後儲存。':'尚未完成校時；班表可先儲存，完成校時後才能準時響鈴。'}catch(e){if(seq!==loadSeq)return;statusEl.textContent='讀取失敗：'+e.message;loadedMonth=''}finally{if(seq===loadSeq){busy=false;controls()}}}
month.onchange=()=>{if(!month.value)return;if(dirty&&!confirm('有尚未儲存的修改，確定切換月份？')){month.value=loadedMonth;return}load()};document.querySelector('#clear').onclick=()=>{selected.clear();review.clear();dirty=true;draw()};document.querySelector('#add').onclick=()=>{if(alarmTimes.length<8){alarmTimes.push('07:00');dirty=true;drawTimes()}};
document.querySelector('#first-only').onchange=()=>{dirty=true;draw()};document.querySelector('#save').onclick=async()=>{if(busy||loadedMonth!==month.value)return;if(mixedTimes&&!confirm('這個月份原本各天有不同響鈴時間。儲存後會把所選上班日統一為下列時間，確定套用？'))return;if(review.size){statusEl.textContent='請先確認橙色日期，再儲存班表。';return}if((selected.size&&!alarmTimes.length)||new Set(alarmTimes).size!==alarmTimes.length){statusEl.textContent='請新增至少一個響鈴時間，且時間不可重複。';return}busy=true;controls();try{const firstOnly=document.querySelector('#first-only').checked;const accepted=await request('/api/local-calendar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:loadedMonth,days:[...selected].sort((a,b)=>a-b),times:alarmTimes,disabled_times:[...disabledTimes],first_consecutive_only:firstOnly})});await waitForSave(accepted.id);dirty=false;mixedTimes=false;const enabledCount=alarmTimes.length-disabledTimes.size;statusEl.textContent=`已儲存 ${loadedMonth}：${selected.size} 天上班、${enabledCount} 個響鈴時間已啟用。${firstOnly?'連續上班只在第一天響鈴。':'每個上班日都會響鈴。'}重新開機也會保留。`}catch(e){statusEl.textContent='儲存失敗：'+e.message}finally{busy=false;controls()}};
async function prepareScheduleImage(file){
 if(file.size>32*1024*1024)throw Error('圖片不可超過 32 MB。');
 const url=URL.createObjectURL(file),img=new Image();
 try{
  await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('圖片無法讀取，請使用 JPG、PNG 或 WebP。'));img.src=url});
  if(!img.naturalWidth||!img.naturalHeight||img.naturalWidth*img.naturalHeight>40000000)throw Error('圖片尺寸過大，請先裁切班表範圍。');
  const ratio=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');
  canvas.width=Math.max(1,Math.round(img.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(img.naturalHeight*ratio));
  const ctx=canvas.getContext('2d');if(!ctx)throw Error('無法處理圖片，請重新開啟頁面。');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',0.85));if(!blob)throw Error('圖片處理失敗，請換一張圖片。');return blob;
 }finally{URL.revokeObjectURL(url)}
}
document.querySelector('#upload').onsubmit=async(e)=>{e.preventDefault();if(busy)return;const file=document.querySelector('#image').files[0];if(!file){aiStatus.textContent='請先選擇班表圖片。';return}if(file.size>32*1024*1024){aiStatus.textContent='圖片不可超過 32 MB。';return}busy=true;controller=new AbortController();controls();const data=new FormData();data.append('month',month.value);let phase='正在處理圖片';aiStatus.textContent=phase+'…';const started=Date.now(),timer=setTimeout(()=>controller?.abort(),60000),progress=setInterval(()=>{aiStatus.textContent=phase+'，已等待 '+Math.floor((Date.now()-started)/1000)+' 秒；可取消後手動選擇日期。'},10000);try{const image=await prepareScheduleImage(file);if(controller.signal.aborted)throw new DOMException('已取消','AbortError');data.append('file',image,'schedule.jpg');phase='正在確認辨識服務連線';aiStatus.textContent=phase+'…';const probeTimer=setTimeout(()=>controller?.abort(),8000);try{const health=await request('/api/health',{signal:controller.signal});if(!health.recognition_ready)throw Error('辨識服務尚未設定')}finally{clearTimeout(probeTimer)}phase='正在上傳並辨識班表';aiStatus.textContent=phase+'…';const d=await request('/api/import',{method:'POST',headers:{'X-Alarm-UI':'1'},body:data,signal:controller.signal});if(d.month!==month.value||!Array.isArray(d.days))throw Error('辨識月份與選擇月份不符');const work=new Set(),uncertain=new Set();for(const day of d.days){const n=Number(day.date.slice(-2));if(day.classification==='work')work.add(n);else if(day.classification==='review')uncertain.add(n)}selected=work;review=uncertain;dirty=true;aiStatus.textContent=`辨識完成：${work.size} 天上班${uncertain.size?'、'+uncertain.size+' 天待確認':''}。請確認下方日期並儲存。`}catch(e){aiStatus.textContent=e.name==='AbortError'?'辨識已取消或連線逾時，已停止等待；原有日期未變更，可直接調整月曆。':'辨識失敗：'+e.message.replace(/[。\s]+$/,'')+'。原有日期未變更，你仍可直接點選月曆。'}finally{clearTimeout(timer);clearInterval(progress);controller=null;busy=false;controls()}};document.querySelector('#cancel').onclick=()=>controller?.abort();
document.querySelector('#clock').onclick=async()=>{try{await request('/api/local-clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({epoch:Math.floor(Date.now()/1000)})});document.querySelector('#clock').hidden=true;statusEl.textContent='已使用此手機／電腦的時間校時。'}catch(e){statusEl.textContent='校時失敗：'+e.message}};
function taipeiToday(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),part=type=>Number(parts.find(value=>value.type===type).value);return{year:part('year'),month:part('month'),day:part('day')}}
function refreshTodayMarker(){const [y,m]=month.value.split('-').map(Number),today=taipeiToday();for(const b of document.querySelectorAll('#days button')){const isToday=y===today.year&&m===today.month&&Number(b.textContent)===today.day;b.classList.toggle('today',isToday);if(isToday)b.setAttribute('aria-current','date');else b.removeAttribute('aria-current');b.setAttribute('aria-label',isToday?b.dataset.label.replace('日，','日，今天，'):b.dataset.label)}}const today=taipeiToday();month.value=today.year+'-'+pad(today.month);load();setInterval(refreshTodayMarker,60000);window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
</script>)HTML";
