#pragma once
static const char CALENDAR_PAGE[]=R"HTML(
<h1>Kevin 與晴晴的上班鬧鐘</h1>
<p>兩人都固定週一到週五上班。週四可使用不同的鬧鐘時間；每一個鬧鐘都能獨立開啟或停用。</p>
<div id="people"></div>
<button id="save" type="button">儲存兩人的鬧鐘</button>
<p id="status" role="status" aria-live="polite">正在讀取設定…</p>
<button id="clock" class="secondary" type="button" hidden>使用此手機時間校時</button>
<p class="help">所有日期與時間固定使用臺北時間（UTC+8）。設定保存在裝置內，重新開機與離線時仍會正常響鈴。</p>
<p><a href="/display">裝置設定與時鐘校對</a> · <a href="/tailnet">Tailscale 連線</a></p>
<style>
.person-card{border:1px solid #d9e0dc;border-radius:24px;padding:24px;margin:20px 0;background:#fff}.person-card h2{margin-top:0}.schedule-group{padding:18px 0;border-top:1px solid #e1e6e3}.schedule-group:first-of-type{border-top:0}.schedule-group h3{margin:0 0 8px}.time-row{display:grid;grid-template-columns:minmax(90px,.7fr) minmax(110px,1fr) minmax(110px,1fr) auto auto;gap:10px;align-items:center;margin:10px 0}.time-row select{width:100%}.alarm-enable{display:flex;align-items:center;gap:8px;white-space:nowrap}.alarm-enable input{width:24px;height:24px}.add-alarm{width:100%;margin-top:8px}@media(max-width:720px){.person-card{padding:18px}.time-row{grid-template-columns:1fr 1fr}.time-row strong{grid-column:1/-1}.time-row .alarm-enable{justify-content:flex-start}.time-row .remove-alarm{width:100%}}
</style>
<script>
const nonce='NONCE',people={kevin:'Kevin',qingqing:'晴晴'},groups={regular:{title:'週一、二、三、五',help:'一般上班日使用這組鬧鐘。'},thursday:{title:'週四',help:'週四使用這組獨立鬧鐘。'}};
let profiles={},busy=true,dirty=false,saveId=0;const statusEl=document.querySelector('#status'),pad=n=>String(n).padStart(2,'0');
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function request(url,options={}){const response=await fetch(url,{...options,headers:{'X-Setup-Nonce':nonce,...options.headers}}),text=await response.text();let data;try{data=JSON.parse(text)}catch{}if(!response.ok){const error=Error(typeof data?.detail==='string'?data.detail:typeof data?.error==='string'?data.error:text||'服務暫時無法回應');error.status=response.status;throw error}if(!data)throw Error('服務回應格式無效');return data}
async function retryRead(url,deadline=Date.now()+30000){let error;while(Date.now()<deadline){try{return await request(url,{cache:'no-store'})}catch(value){error=value;await pause(750)}}throw error||Error('裝置暫時無法回應')}
function key(group,disabled=false){return(disabled?'disabled_':'')+group+'_times'}
function markDirty(){dirty=true;render()}
function render(){const root=document.querySelector('#people');root.replaceChildren();for(const [person,name] of Object.entries(people)){const card=document.createElement('section');card.className='person-card';const heading=document.createElement('h2');heading.textContent=name;card.append(heading);const note=document.createElement('p');note.textContent='固定週一到週五上班';card.append(note);for(const [group,copy] of Object.entries(groups)){const section=document.createElement('div');section.className='schedule-group';const title=document.createElement('h3');title.textContent=copy.title;section.append(title);const help=document.createElement('p');help.className='help';help.textContent=copy.help;section.append(help);const list=document.createElement('div'),times=profiles[person]?.[key(group)]||[],disabled=new Set(profiles[person]?.[key(group,true)]||[]);times.forEach((value,index)=>list.append(timeRow(person,group,index,value,disabled.has(value))));if(!times.length){const empty=document.createElement('p');empty.className='help';empty.textContent='尚未設定鬧鐘。';list.append(empty)}section.append(list);const add=document.createElement('button');add.type='button';add.className='secondary add-alarm';add.textContent='＋ 新增鬧鐘時間';add.disabled=busy||times.length>=8;add.onclick=()=>{profiles[person][key(group)].push('07:00');markDirty()};section.append(add);card.append(section)}root.append(card)}document.querySelector('#save').disabled=busy}
function timeRow(person,group,index,value,isDisabled){const row=document.createElement('div');row.className='time-row';const title=document.createElement('strong');title.textContent='鬧鐘 '+(index+1);row.append(title);const [hour,minute]=value.split(':');for(const [unit,current,max] of [['時',hour,24],['分',minute,60]]){const select=document.createElement('select');select.setAttribute('aria-label',`${people[person]} ${groups[group].title}第 ${index+1} 個鬧鐘的${unit}`);for(let n=0;n<max;n++){const option=document.createElement('option');option.value=pad(n);option.textContent=pad(n)+' '+unit;select.append(option)}select.value=current;select.disabled=busy;select.onchange=()=>{const old=profiles[person][key(group)][index],parts=old.split(':');parts[unit==='時'?0:1]=select.value;const changed=parts.join(':'),off=profiles[person][key(group,true)],disabledIndex=off.indexOf(old);profiles[person][key(group)][index]=changed;if(disabledIndex>=0)off[disabledIndex]=changed;markDirty()};row.append(select)}const enableLabel=document.createElement('label');enableLabel.className='alarm-enable';const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=!isDisabled;enabled.disabled=busy;enabled.onchange=()=>{const value=profiles[person][key(group)][index],off=profiles[person][key(group,true)],at=off.indexOf(value);if(enabled.checked&&at>=0)off.splice(at,1);if(!enabled.checked&&at<0)off.push(value);markDirty()};enableLabel.append(enabled,document.createTextNode('啟用'));row.append(enableLabel);const remove=document.createElement('button');remove.type='button';remove.className='secondary remove-alarm';remove.textContent='移除';remove.disabled=busy;remove.onclick=()=>{const value=profiles[person][key(group)][index],off=profiles[person][key(group,true)],at=off.indexOf(value);if(at>=0)off.splice(at,1);profiles[person][key(group)].splice(index,1);markDirty()};row.append(remove);return row}
function valid(){for(const person of Object.keys(people))for(const group of Object.keys(groups)){const times=profiles[person][key(group)];if(new Set(times).size!==times.length){statusEl.textContent=`${people[person]}的${groups[group].title}有重複時間。`;return false}}return true}
async function waitForSave(id){const deadline=Date.now()+45000;while(Date.now()<deadline){try{const result=await request('/api/local-calendar/save-status?id='+id,{cache:'no-store'});if(result.state==='saved')return;if(result.state==='error')throw Error(result.message)}catch(error){if(error.status&&error.status<500)throw error}await pause(750)}throw Error('裝置連線不穩，無法確認儲存結果；請重新整理確認，不要連續按儲存')}
async function submitSave(payload,requestId){let error;for(let attempt=0;attempt<6;attempt++){try{return await request('/api/local-calendar',{method:'POST',headers:{'Content-Type':'application/json','X-Save-Request':requestId},body:JSON.stringify(payload)})}catch(value){error=value;if(error.status&&error.status<500)throw error;await pause(750*(attempt+1))}}const current=await retryRead('/api/local-calendar?mode=weekly');if(JSON.stringify(current.weekly_profiles)===JSON.stringify(payload.weekly_profiles))return{saved:true};throw error||Error('裝置連線中斷，尚未確認儲存結果')}
async function load(){busy=true;render();try{const data=await retryRead('/api/local-calendar?mode=weekly');profiles=data.weekly_profiles;document.querySelector('#clock').hidden=data.clock_ready;dirty=false;statusEl.textContent=data.clock_ready?'可設定兩人的鬧鐘，完成後按下儲存。':'尚未完成校時；設定可先儲存，完成校時後才能準時響鈴。'}catch(error){statusEl.textContent='讀取失敗：'+error.message}finally{busy=false;render()}}
document.querySelector('#save').onclick=async()=>{if(busy||!valid())return;busy=true;render();statusEl.textContent='正在儲存，連線短暫中斷時會自動確認，請不要重複按。';const requestId=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()),payload={weekly_profiles:profiles};try{const accepted=await submitSave(payload,requestId);if(!accepted.saved){saveId=accepted.id;await waitForSave(saveId)}const current=await retryRead('/api/local-calendar?mode=weekly');if(JSON.stringify(current.weekly_profiles)!==JSON.stringify(profiles))throw Error('裝置回傳的設定不同，請重新整理後再試');dirty=false;statusEl.textContent='已儲存 Kevin 與晴晴的每週鬧鐘；週一到週五會依各自設定響鈴，週四使用獨立時間。'}catch(error){statusEl.textContent='儲存失敗：'+error.message}finally{busy=false;render()}};
document.querySelector('#clock').onclick=async()=>{try{await request('/api/local-clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({epoch:Math.floor(Date.now()/1000)})});document.querySelector('#clock').hidden=true;statusEl.textContent='已使用此手機／電腦的時間校時。'}catch(error){statusEl.textContent='校時失敗：'+error.message}};
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});load();
</script>
)HTML";
