#pragma once
#include "calendar_policy.h"
#include "calendar_page.h"

String localCalendarMonthKey(int year,int month){char key[8];snprintf(key,sizeof(key),"%04d-%02d",year,month);return String(key);}
std::set<int64_t> knownLocalWorkDates(JsonVariantConst months){std::set<int64_t> dates;for(JsonPairConst entry:months.as<JsonObjectConst>()){int year,month;if(!localcalendar::month(entry.key().c_str(),year,month))continue;for(JsonVariantConst day:entry.value()["days"].as<JsonArrayConst>())dates.insert(localcalendar::epoch(year,month,day.as<int>(),0,0));}for(const auto &alarm:alarms){if(!alarm.id.startsWith("local-"))continue;time_t value=alarm.epoch;tm date;localtime_r(&value,&date);String key=localCalendarMonthKey(date.tm_year+1900,date.tm_mon+1);if(!months[key].is<JsonObjectConst>())dates.insert(localcalendar::epoch(date.tm_year+1900,date.tm_mon+1,date.tm_mday,0,0));}return dates;}
void localCalendarRoutes(){
 server.on("/calendar",HTTP_GET,[]{String page=CALENDAR_PAGE;page.replace("NONCE",setupNonce);server.send(200,"text/html; charset=utf-8",devicePage(page));});
 server.on("/api/local-calendar",HTTP_GET,[]{if(!localNonce())return;int year,month;String value=server.arg("month");if(!localcalendar::month(value.c_str(),year,month)){server.send(400,"text/plain; charset=utf-8","月份格式無效");return;}JsonDocument d;d["local"]=localSchedule;d["clock_ready"]=clockValid();d["first_consecutive_only"]=firstConsecutiveOnly;const auto knownDates=knownLocalWorkDates(calendarMonths.as<JsonVariantConst>());d["previous_day_work"]=knownDates.count(localcalendar::epoch(year,month,1,0,0)-86400)>0;auto days=d["days"].to<JsonArray>();auto times=d["times"].to<JsonArray>();std::vector<int> selected;std::vector<String> hours;std::set<std::pair<int,int>> slots;if(calendarMonths[value].is<JsonObject>()){d["days"]=calendarMonths[value]["days"];d["times"]=calendarMonths[value]["times"];d["disabled_times"]=calendarMonths[value]["disabled_times"];d["mixed_times"]=false;String out;serializeJson(d,out);server.send(200,"application/json",out);return;}for(const auto &alarm:alarms){if(alarm.id.startsWith("test-"))continue;time_t at=alarm.epoch;tm date;localtime_r(&at,&date);if(date.tm_year+1900!=year||date.tm_mon+1!=month)continue;slots.emplace(date.tm_mday,date.tm_hour*60+date.tm_min);if(std::find(selected.begin(),selected.end(),date.tm_mday)==selected.end())selected.push_back(date.tm_mday);char text[6];snprintf(text,sizeof(text),"%02d:%02d",date.tm_hour,date.tm_min);if(std::find(hours.begin(),hours.end(),String(text))==hours.end())hours.push_back(text);}d["mixed_times"]=localcalendar::mixedTimes(slots);std::sort(selected.begin(),selected.end());std::sort(hours.begin(),hours.end());for(int day:selected)days.add(day);for(const auto &at:hours)times.add(at);String out;serializeJson(d,out);server.send(200,"application/json",out);});
 server.on("/api/local-calendar",HTTP_POST,[]{if(!localNonce())return;if(scheduleStorageFault.load()){server.send(409,"application/json","{\"error\":\"schedule-storage-fault\",\"detail\":\"班表儲存狀態不明；重開前請勿修改\"}");return;}String input=server.arg("plain");if(input.length()>4096){server.send(413,"text/plain; charset=utf-8","班表資料過大");return;}uint32_t id=0;if(!enqueueScheduleWork(ScheduleOrigin::Local,std::move(input),id)){server.send(409,"text/plain; charset=utf-8","班表正在驗證或儲存，請稍後重試");return;}localSaveId=id;localSaveState="pending";localSaveMessage="正在驗證並儲存";server.send(202,"application/json",String("{\"pending\":true,\"id\":")+id+"}");});
 server.on("/api/local-calendar/save-status",HTTP_GET,[]{if(!localNonce())return;uint32_t id=server.arg("id").toInt();if(!id||id!=localSaveId){server.send(404,"text/plain; charset=utf-8","找不到這次儲存作業");return;}JsonDocument d;d["id"]=id;d["state"]=localSaveState;d["message"]=localSaveMessage;String out;serializeJson(d,out);server.send(200,"application/json",out);});
 server.on("/api/local-clock",HTTP_POST,[]{if(!localNonce())return;JsonDocument d;if(server.arg("plain").length()>128||deserializeJson(d,server.arg("plain"))||!d["epoch"].is<int64_t>()||d["epoch"].as<int64_t>()<1704067200||d["epoch"].as<int64_t>()>=4102444800LL){server.send(400,"text/plain; charset=utf-8","校時資料無效");return;}timeval tv={};tv.tv_sec=d["epoch"].as<int64_t>();settimeofday(&tv,nullptr);server.send(200,"application/json","{\"ok\":true}");});
}
