[env:cube-tft]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_port = /dev/cu.usbmodem101
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -DCUBE_TFT=1
lib_deps =
  bblanchon/ArduinoJson@7.3.1
  adafruit/Adafruit ST7735 and ST7789 Library@1.11.0
  adafruit/Adafruit SSD1306@2.5.13
  ricmoo/QRCode@0.0.1
